@startuml
package presentation {
    +class Main {
        +{static}main(args: String[]): void
    }

    +class GameUI {
        -gameState: GameStateLayer
        -localizedMessages: ResourceBundle

        +GameUI(): void

        +handleSetupGame(): void
        -chooseLanguage(): void
        -chooseGame(): void
        -chooseNumberOfPlayers(): void

        -runDisplayLoop(): void
        -requestNextMove(): void
        -handleDisplayTurnEndResult(): void

        -handleShowEndGame(): void
    }
}

package domain {
    +class GameStateLayer {
        -gameLogicLayer: GameLogicLayer
        -currentPlayerTurn: int
        -currentPlayerNumberOfTurns: int

        -attackQueue: List<Integer>
        -attackCounter: int
        -numberOfAttacks: int
        -attacked: boolean

        -isReversed: boolean
        -rand: Random

        -deck: GameDeck
        -turnTracker: int[]
        -numberOfPlayers: int

        -{static}{final} PLAYER_HAND_EMPTY_EXCEPTION: String
        -{static}{final} INVALID_PLAYER_INDEX_EXCEPTION: String
        -{static}{final} INVALID_GAME_TYPE_EXCEPTION: String
        -{static}{final} NO_PLAYERS_EXCEPTION: String
        -{static}{final} OUT_OF_BOUNDS_PLAYER_INDEX_EXCEPTION: String
        -{static}{final} PLAYER_DEAD_EXCEPTION: String
        -{static}{final} CARD_INDEX_OUT_OF_BOUNDS_EXCEPTION: String
        -{static}{final} CARD_TYPE_NOT_FOUND_EXCEPTION: String
        -{static}{final} INVALID_NUMBER_OF_PLAYERS_EXCEPTION: String
        -{static}{final} NUMBER_OF_TURNS_OUT_OF_BOUNDS_EXCEPTION: String


        +GameStateLayer(): void
        ~setGameGameType(gameSelection: String): boolean
        ~setNumberOfPlayers(playerNum: int): boolean
        ~getNumCardsInHand(playerID: int): int

        +nextMove(): String

    }
    +class Player {
        -playerID: int
        -numTurnsRemaining: int
        -rand: Random
        -isCursed: boolean
        -isDead: boolean

        -{static}{final} MUST_ADD_DEFUSE_CARD_EXCEPTION: String
        -{static}{final} INVALID_INDEX_EXCEPTION: String
        -{static}{final} NO_CARD_FOUND_EXCEPTION: String

        ~Player(playerID: int, instantiator: Instantiator): void
        ~getPlayerID(): int
        ~getIsDead(): boolean
        ~setIsDead(): void
        ~getIsCursed(): boolean
        ~setCursed(isCursed: boolean): void
    }
    +interface GameLogicInterface {

    }
    +interface DeckInitializationInterface {
        +generateGameDeck(): Card[]
    }
    +class GameDeck {
        -availableCards: Card[]
        -playerHands: Map<int, Card>
        -initializationAlgorithm: DeckInitializationInterface

        -{static}{final} DECK_FULL_EXECEPTION: string
        -{static}{final} DRAW_FROM_EMPTY_DECK_EXCEPTION: string
        -{static}{final} NEGATIVE_INDEX_EXCEPTION: string
        -{static}{final} INDEX_GREATER_THAN_DECK_SIZE_EXCEPTION: string
        -{static}{final} MISMATCH_ORDER_SIZE_EXCEPTION: string
        -{static}{final} INDEX_OUT_OF_RANGE_EXCEPTION: string

        +GameDeck(numPlayers: int): boolean
        -initializeDeck(): boolean
        -shuffleDeck(numTimes: int): boolean

        ~drawCard(playerNum: int, fromBottom: boolean): boolean
        ~insertCard(playerID: int, cardType: CardType, numberOfCards: int, bottom: boolean): boolean
        ~removeBombs(): int

        ~getCardTypeAtIndex(index: int): CardType
        ~reorderDeckCards(newOrderIndices: int[], cardsToReorder: List<Card>): void

        -addedOutOfBounds(numberOfCards: int): boolean
        -checkIfExplodingKitten(index: int): boolean
        -checkIfIndexOutOfRange(index: int): boolean
    }
    +class Card {
        -cardType: CardType
        -isMarked: boolean
        -isFacedUp: boolean

        ~Card(cardType: CardType): void
        ~getCardType(): CardType
        ~markCard(): void
        ~checkIfMarked(): boolean
        ~setFacedUp(): void
        ~checkIfFacedUp(): void
    }
    +enum CardType {
        NOPE,
        DEFUSE,
        ATTACK,
        SHUFFLE,
        SKIP,
        SEE_THE_FUTURE,
        CAT_ONE,
        CAT_TWO,
        CAT_THREE,
        CAT_FOUR,
        EXPLODING_KITTEN,
        STREAKING_KITTEN,
        SWAP_TOP_AND_BOTTOM,
        GARBAGE_COLLECTION,
        CURSE_OF_THE_CAT_BUTT,
        ALTER_THE_FUTURE,
        CATOMIC_BOMB,
        SUPER_SKIP,
        MARK,
        IMPLODING_KITTEN,
        REVERSE,
        FERAL_CAT,
        TARGETED_ATTACK,
        DRAW_FROM_THE_BOTTOM;

        - {final} gameType: GameType
        ~CardType(gameType: GameType): void
    }

    +class ExplodingKittens {

    }
    +class StreakingKittens {

    }
    +class ImplodingKittens {

    }
    +class CardSpecialEvents {
        -playCurseOfTheCatButt(): void
        -playSpecialComboTwoCards(cardType: CardType): void
        -playMark(): void
        -playCatomicBomb(): void
        -playReverse(): void
        -playSpecialComboThreeCards(cardType: CardType): void
        -playSeeTheFuture(): void
        -playShuffle(): void
        -playSkip(superSkip: boolean): void
        -playAlterTheFuture(): void
        -playSpecialCombo(): int
        -playNope(playerIndex: int): void
        -playExplodingKitten(playerIndex: int): boolean
    }


    +class GameLogicLayer {
    }
}

Main-->GameUI

GameUI-->GameStateLayer
GameStateLayer-->GameLogicLayer
GameStateLayer-->GameDeck

GameDeck-->Card
GameStateLayer-->Player
GameDeck-->DeckInitializationInterface

Card-->CardType

GameLogicLayer-->GameLogicInterface

GameLogicInterface--|>ExplodingKittens
GameLogicInterface--|>StreakingKittens
GameLogicInterface--|>ImplodingKittens

ExplodingKittens..>CardSpecialEvents
StreakingKittens..>CardSpecialEvents
ImplodingKittens..>CardSpecialEvents


@enduml