@startuml
package presentation {
    +class Main {
        +{static}main(args: String[]): void
    }

    +class GameUI {
        -gameState: GameStateLayer
        -localizedMessages: ResourceBundle

        +GameUI(): void

        +handleSetupGame(): void
        -chooseLanguage(): void
        -chooseGame(): void
        -chooseNumberOfPlayers(): void

        -runDisplayLoop(): void
        -handleDisplayTurnEndResult(): void

        -handleShowEndGame(): void
    }
}

package domain {
    +class GameStateLayer {
        -gameLogic: GameLogicLayer
        -players: Player[]

        +GameStateLayer(): void
        +setGameGameType(gameSelection: String): boolean

        +setNumberOfPlayers(playerNum: int): boolean
        -generatePlayer


    }
    +class Player {

    }
    +class GameLogicLayer {

    }
    +class Deck {

    }
    +class Card {

    }
    +class GameLogicType {

    }
}

Main-->GameUI

GameUI-->GameStateLayer
GameStateLayer-->Player
GameStateLayer-->GameLogicLayer

GameLogicLayer-->GameLogicType
GameLogicLayer-->Deck

Deck-->Card

@enduml